replicaCount: 1

fullnameOverride: $REPO_NAME

image:
  repository: "$DOCKER_USER/$REPO_NAME"
  tag: "$SHORT_SHA"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

environment:
  name: development

backend:
  url: http://k8s-backend

resources:
  requests:
    memory: "32Mi"
    cpu: "10m"
  limits:
    memory: "256Mi"
    cpu: "100m"